In [1]:
import numpy as np
from numpy import random

# Part A

### 1. Creating NumPy arrays

###### a) Check the version of NumPy and create 1D, 2D arrays.


In [2]:
print(np.__version__)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

1.22.4


###### b) Check the data type and dimension of created arrays

In [3]:
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


###### c) Find the size of each element in the arrays.

In [4]:
print(arr1.nbytes)
print(arr2.nbytes)

20
24


###### d) Find the number of rows and columns of 2D array.

In [5]:
arr2.shape

(2, 3)

###### e) An array of shape (2, 3) given, reshape the array into (3, 2).

In [6]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 2. Slicing of arrays 

###### a) A 1D array is given as [4, 5, 6, 3, 9, 7]. Slice the array to get [6, 3, 9].

In [7]:
arr = [4, 5, 6, 3, 9, 7]
arr[2:5]

[6, 3, 9]

###### b) A 2D array is given as [[1, 2, 3] [4, 5, 6]]. Slice the array to get [ [1, 2]].

In [8]:
arr =  np.array([[1, 2, 3],[4, 5, 6]])
arr[:1,:2]

array([[1, 2]])

### 3. Join and splitting of NumPy Arrays  

###### a) Concatenate two 1D arrays [4,5,6,7] and [3,4,1].

In [9]:
arr1 =  [4,5,6,7]
arr2 = [3,4,1]
arr1+arr2

[4, 5, 6, 7, 3, 4, 1]

###### b) Perform concatenation of two 2D arrays in row-by-row manner.

In [10]:
arr1 =  np.array([[1, 2, 3],[4, 5, 6]])
arr2 =  np.array([[7, 8, 9],[10,11, 12]])
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

###### c) Split the array [4, 5, 6, 3, 9,] into 3 sub-arrays.

In [11]:
arr = np.array([4, 5, 6, 3, 9])
new_arr = np.array_split(arr,3)
new_arr

[array([4, 5]), array([6, 3]), array([9])]

###### d) Split the array the 2D array [[ 1, 2, 3] [ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]] into 3 sub-arrays.

In [12]:
arr = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
new_arr = np.array_split(arr,3)
new_arr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

### 4. Searching elements in an array

###### a) Given an array [1, 2, 3, 4, 5, 4, 4]. Find the index of element 4.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(arr == 4))

(array([3, 5, 6], dtype=int64),)


###### b) Given a 2d array [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]]. Find the index of element 5.

In [14]:
arr = np.array( [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
print(np.where(arr == 5))

(array([1], dtype=int64), array([1], dtype=int64))


###### c) Given an array [1, 2, 3, 4, 5, 6, 7, 8], find out the indices of odd elements and even elements.

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Indices for odd elements: ",np.where(arr%2 != 0))
print("Indices for even elements: ",np.where(arr%2 == 0))

Indices for odd elements:  (array([0, 2, 4, 6], dtype=int64),)
Indices for even elements:  (array([1, 3, 5, 7], dtype=int64),)


### 5. Sorting of Arrays

###### a) Sort the elements of given 1D array [6, 5, 1, 2, 9, 10, 36, 7] in ascending and descending order.

In [16]:
arr = np.array([6, 5, 1, 2, 9, 10, 36, 7])
arr = np.sort(arr,axis=0)
print("Ascending order: ",arr)
arr = np.sort(arr)[::-1]
print("Descending order",arr)

Ascending order:  [ 1  2  5  6  7  9 10 36]
Descending order [36 10  9  7  6  5  2  1]


###### b) Sort the elements of given 2D array [[5, 3, 7], [8, 10, 6], [40, -2, 7]] in ascending and descending order.

In [17]:
arr = np.array([[5, 3, 7], [8, 10, 6], [40, -2, 7]])
arr = np.sort(arr,axis = 1)
print("Ascending order: ",arr)
arr = -np.sort(-arr, axis=0)
print("Descending order",arr)

Ascending order:  [[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]
Descending order [[ 6  8 40]
 [ 3  7 10]
 [-2  5  7]]


### 6. Random number generation in NumPy arrays

###### a) Generate a 1-D array containing 6 random integers from 0 to 20.

In [18]:
arr = np.random.randint(0,21,6)
arr

array([ 8, 10, 14, 18, 20, 10])

###### b) Generate a 1-D array containing 5 random floats.

In [19]:
arr = np.random.rand(5)
arr

array([0.34717395, 0.42769848, 0.54892707, 0.85037899, 0.0042083 ])

###### c) Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 50.

In [20]:
arr = np.random.randint(50,size=(3,5))
arr

array([[25, 18, 38,  8, 15],
       [22, 16, 12, 10, 15],
       [11, 29, 24, 16, 15]])

###### d) Generate a 2-D array with 3 rows, each row containing 5 random numbers.

In [21]:
arr = np.random.rand(3,5)
arr

array([[0.57196431, 0.13464299, 0.09690317, 0.73344678, 0.76412702],
       [0.60625595, 0.25171147, 0.95468839, 0.37232015, 0.29923401],
       [0.40552417, 0.34408469, 0.20135767, 0.21534572, 0.52384531]])

###### e) Given a 1-D array [6, 5, 1, 2, 9, 10, 36, 7]. Shuffle the elements of the array randomly.


In [22]:
arr = np.array([6, 5, 1, 2, 9, 10, 36, 7])
np.random.shuffle(arr)
arr


array([ 1,  7,  9,  6,  5, 10,  2, 36])

###### f) Given a 2-D array [[ 1, 2, 3] [ 4, 5, 6][ 7, 8, 9] [10, 11, 12]]. Shuffle the elements of the array randomly.

In [23]:
arr = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
np.random.shuffle(arr)
arr

array([[ 4,  5,  6],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 7,  8,  9]])

# Part B

In [24]:
import pandas as pd
import csv

In [25]:
#1&2
with open("winequality-red.csv", 'r') as f:
    arr = list(csv.reader(f, delimiter=";"))

###### 3. Convert the wine_data into NumPy Array

In [26]:
arr = np.array(arr[1:], dtype=float)
arr

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

###### 4. Check the shape (5)

In [27]:
arr.shape

(1599, 12)

###### 5. Slicing the matrix: From the matrix wine_data, create a new variable:

In [28]:
#a
y = arr[:,-1]
y.shape

(1599,)

In [29]:
#b
x = arr[:,:-1]
x.shape

(1599, 11)

###### 6. Compute the following statistical values using NumPy in-built functions wherever possible.

In [30]:
#a
mean = x.mean(axis=0)
mean

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311])

In [31]:
#b
vals,counts = np.unique(y, return_counts=True)
index = np.argmax(counts)
print(vals[index])

5.0


In [32]:
#c
std = np.std(x,axis=None)
std

16.726533979432844